<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'saved' => 'salvata',
  'Your new seed is' => 'La tua nuova sequenza di parole è:',
  '</br></br>Please enter a password to encrypt the seed.' => '</br></br>Per favore inserisci una password per cifrare il seed.',
  '<b>Write the seed and keep it in a safe place; if you lose it you will not be able to restore your wallet and you will lose all the funds.</b>' => '<h3 class="text-warning">Scrivi adesso la sequenza di parole e conservala in un luogo sicuro.</h3><br>Se la perdi non sarai in grado di ripristinare il tuo portafoglio e perderai tutti i fondi.',
  '<br>(<small><i>Minimum 8 characters, alphanumeric, uppercase, lowercase and special</i></small>)' => '<br>(<small><i>Minimo 8 caratteri, alfanumerico, maiuscolo, minuscolo e speciale</i></small>)',
  '<p>Your new seed is:</p><p class=\'alert alert-danger\'><strong>{seed}</strong></p>' => '<p>La tua nuova sequenza di parole è:</p><p class=\'alert alert-danger\'><strong>{seed}</strong></p>',
  'Amount is higher than Balance.' => 'Importo maggiore del Conto.',
  'Checking...' => 'Controllando...',
  'Confirm' => 'Conferma',
  'Disable' => 'Disabilita',
  'Enable' => 'Abilita',
  'Fast' => 'Veloce',
  'Invalid Seed!' => 'Sequenza di parole non valida! Controlla che siano 12 in tutto e che non ci siano spazi in eccesso.',
  'Invalid amount!' => 'Importo non valido!',
  'Invalid amount! Use a maximum of 2 decimals.' => 'Importo non valido. Utilizza massimo 2 cifre decimali.',
  'Use a maximum of 2 decimal places.' => 'Utilizza massimo 2 cifre decimali.',
  'New transactions found. Do you want to view them?' => 'Nuove transazioni trovate. Vuoi visualizzarle?',
  'No' => 'No',
  'Notifications are locked' => 'Le notifiche sono bloccate',
  'Password too short! Use at least 8 characters.' => 'Password troppo corta. Utilizza almeno 8 cratteri.',
  'Push Not Supported' => 'Messaggi push non supportati',
  'Recipient address not entered.' => 'Indirizzo del destinatario non inserito.',
  'Standard' => 'Standard',
  'Synchronizing the blockchain: {number} blocks left.' => 'Sincronizzando la blockchain: mancano {number} blocchi.',
  'Transaction status with a price of {price} is changed in {status}. Do you want to view it?' => 'Lo stato della transazione di importo {price} è cambiato in {status}. Vuoi visualizzarla?',
  'Transaction status with a price of {price} is now completed. Do you want to view it?' => 'La transazione di importo {price} è stata completata. Vuoi visualizzarla?',
  'Transactions updated. Do you want to view them?' => 'Transazioni aggiornate. Vuoi visualizzarle?',
  'Unable to verify destination address.' => 'Impossibile verificare l\'indirizzo del destinatario.',
  'Wrong destination address.' => 'Indirizzo del destinatario errato.',
  'Yes' => 'Si',
  '[Bolt] - New message' => '[Bolt] - Nuovo messaggio',
  'loading...' => 'caricando...',
  'Medium' => 'Media',
  'Strong' => 'Forte',
  'Too short and ' => 'Troppo corta e ',
  'Weak' => 'Banale',
);
