<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'You generated a new invoice.' => 'Hai generato una nuova richiesta di pagamento.',
  'You generated a new token invoice.' => 'Hai generato una nuova richiesta di pagamento.',
  'New transaction'=>'Nuova transazione',
  'A transaction has been completed.' => 'Una transazione è stata completata.',
  '{application} - Contact' => '{application} - Contatto',
  '{application} - Password Reset' => '{application} - Reset password',
  '{application} - User signup' => '{application} - Registrazione utente',
  'A transaction you "{alias}" has been completed.' => '@@Una transazione che hai "{alias}" è stata completata.@@',
  'You have "{alias}" a new transaction.' => '@@Hai "{alias}" una nuova transazione.@@',
  'received' => '@@ricevuto@@',
  'sent' => '@@inviato@@',
  '{param0} is following you.' => '{param0} ti ha aggiunto ai contatti.',
  '{param0} unfollowed you.' => '{param0} ti ha rimosso dai contatti.',
  'A "{alias}" transaction has been completed.' => 'Una transazione "{alias}" è stata completata.',
  'Ether' => 'Ether',
  'New message' => 'Nuovo messaggio',
  'Token' => 'Token',
  'You have sent a new "{alias}" transaction.' => 'Hai inviato una nuova transazione "{alias}".',
  'complete' => 'Completata',
  'new' => 'nuova',
  'You have sent a new transaction.' => 'Hai inviato una nuova transazione.',
  'A transaction you received has been completed.' => 'Una transazione che hai ricevuto è stata completata.',
  'A transaction you sent has been completed.' => 'Una transazione che hai inviato è stata completata.',
  'You received a new transaction.' => 'Hai ricevuto una nuova transazione.',
  'new' => 'in corso...',
  'complete' => 'completata',
  'New' => 'Nuova',
  'Complete' => 'Completata',
  'failed' => 'allarme',
  'Failed' => 'Allarme',
);
